### PR TITLE
fix color issue in calendar

### PR DESCRIPTION
**Pull request by osendott**
edited colors in calendar to the blue-green (green) color as per our discussion earlier. should be what you were looking for. 

also pushing a formatted version of the compiled stylesheet, for reference only, it's not loaded or used in the theme, just what I'm combing through to look for any more instances of the compiler missing a thing or two. I committed them separately in case you don't want to accept that one, just thought it may come in handy if I have any questions about whether something was compiled correctly or not.

I'll go through the code some more later on tonight.

oh, also, is my formatting ok in the custom.css??

I'll start figuring out this stylus stuff too, first time I've used a pre-processor for css.

### CODE REVIEW

**Comment by alex285** [comment]
You should commit with stylus so I can merge directly, or even better to give you access so you can push directly!
It is easy to learn stylus and you will love it!

**Comment by osendott** [comment]
I'll read up on it this evening, doesn't look all that much different really. 
I'm old (31) and set in my ways, but I'll try to adapt, there was a time I didn't care for css either haha

**Comment by osendott** [comment]
if you get a chance, clone my repo one last time, and see what you think of the highlight-image on the panel instead of that big green box.. (the color will need tweaked to work with EvoPop of course)

**Comment by osendott** [comment]
my -dist repo that is

**Comment by alex285** [comment]
not bad idea, but definitely not with those colors.
If you try something simpler with 2 colors only?

Btw it isnt green, it is light blue :)

**Comment by osendott** [comment]
that may be more up your alley, same color as green ( :P ) in theme (#37B9A5) and just a simple line above selection

**Comment by osendott** [comment]
btw, if you want to discontinue chatting it up in the issue that is now closed on github, my e-mail is william.osendott[at]gmail[dot]com

**Pull request closed without merging**
